# Generated by Django 4.2.2 on 2023-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Product_image",
            new_name="product_image",
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("MB", "men-blazers"),
                    ("MST", "men-shirts"),
                    ("MP", "men-pants"),
                    ("MS", "men-shoes"),
                    ("MH", "men-hats"),
                    ("MEW", "men-eye-wears"),
                    ("TW", "top-wear"),
                    ("BW", "bottom-wear"),
                    ("C", "Chudidar"),
                    ("WS", "women-shoes"),
                    ("J", "jewellery"),
                    ("B", "boy"),
                    ("G", "girl"),
                ],
                max_length=4,
            ),
        ),
    ]
