# Generated by Django 4.2.2 on 2023-06-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_product_category_designer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="designer",
            old_name="user",
            new_name="username",
        ),
    ]
