# Generated by Django 4.2.2 on 2023-06-23 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0009_designer_designer_image_designer_full_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="designer",
            old_name="password",
            new_name="designer_code",
        ),
        migrations.AlterField(
            model_name="designer",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
