# Generated by Django 4.2.2 on 2023-06-23 18:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_designer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designer",
            name="designer_code",
            field=models.IntegerField(
                default=app.models.generate_random_number, unique=True
            ),
        ),
    ]
