# Generated by Django 4.2.2 on 2023-06-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_designer_designer_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designer",
            name="phone",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
