# Generated by Django 4.2.2 on 2023-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_designer_des_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="designer",
            name="category",
            field=models.CharField(
                choices=[
                    ("MB", "men-blazers"),
                    ("MST", "men-shirts"),
                    ("MP", "men-pants"),
                    ("MS", "men-shoes"),
                    ("MH", "men-hats"),
                    ("MEW", "men-eye-wears"),
                    ("TW", "top-wear"),
                    ("BW", "bottom-wear"),
                    ("C", "Chudidar"),
                    ("WS", "women-shoes"),
                    ("J", "jewellery"),
                    ("S", "saree"),
                    ("B", "boy"),
                    ("G", "girl"),
                    ("D", "designer"),
                ],
                default=0,
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("MB", "men-blazers"),
                    ("MST", "men-shirts"),
                    ("MP", "men-pants"),
                    ("MS", "men-shoes"),
                    ("MH", "men-hats"),
                    ("MEW", "men-eye-wears"),
                    ("TW", "top-wear"),
                    ("BW", "bottom-wear"),
                    ("C", "Chudidar"),
                    ("WS", "women-shoes"),
                    ("J", "jewellery"),
                    ("S", "saree"),
                    ("B", "boy"),
                    ("G", "girl"),
                    ("D", "designer"),
                ],
                max_length=4,
            ),
        ),
    ]
