# Generated by Django 4.2.2 on 2023-06-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_designer_category_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designer",
            name="des_category",
            field=models.CharField(
                choices=[("MD", "men_designers"), ("WD", "women_designers")],
                max_length=4,
            ),
        ),
    ]
