# Generated by Django 4.2.2 on 2023-06-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_designer_des_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designer",
            name="category",
        ),
        migrations.RemoveField(
            model_name="designer",
            name="des_category",
        ),
    ]
