# Generated by Django 4.2.2 on 2023-06-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_tempdesignerplaced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempdesignerplaced",
            name="customer",
        ),
    ]
