# Generated by Django 4.2.2 on 2023-06-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_remove_tempdesignerplaced_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designerplaced",
            name="status",
            field=models.CharField(
                choices=[("Accepted", "Accepted"), ("Cancel", "Cancel")],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
