# Generated by Django 4.2.2 on 2023-07-11 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_alter_designer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designer",
            name="phone",
            field=models.CharField(
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+?1?\\d{9,10}$")
                ],
            ),
        ),
        migrations.CreateModel(
            name="DesignerWorks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("works_img", models.ImageField(upload_to="works_img")),
                ("descriptions", models.TextField(max_length=500)),
                (
                    "designer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="app.designer",
                    ),
                ),
            ],
        ),
    ]
