# Generated by Django 4.2.2 on 2023-07-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_alter_designer_phone_designerworks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designerworks",
            name="designer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.designer"
            ),
        ),
    ]
