# Generated by Django 4.2.2 on 2023-07-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_alter_designerworks_designer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designerworks",
            name="designer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works",
                to="app.designer",
            ),
        ),
    ]
